### ISSUE TITLE
Move away from KO-ish templating syntax

### ISSUE THREAD

**Issue by Munawwar** [Munawwar/lithium-ui#2]
Move away form KO templating syntax and make it more like React/Angular

So the following KO template:
```html
<div class="box" data-bind="if: condition, attr: {title: title}, css: {rounded: isRounded}, style: {color: color}">
    <!-- ko if: condition -->
       <span data-bind="text: text"></span>
    <!-- /ko -->
</div>
```

would become:
```html
<div class="box" title={title} li-if="condition" li-class="rounded: isRounded" li-style="color: color">
    {if: condition}
       <span>{text}</span>
    {/}
</div>
```

`{/}` closes the if statement.

**Comment by rolandliwag** [comment]
isRounded looks like it should be a boolean but there's some confusion between the KO syntax and the Li syntax.

**Comment by Munawwar** [comment]
How about now? `class="box {rounded:isRounded}"`. Looks weird?

**Comment by rolandliwag** [comment]
It's a little unconventional but I think it's understandable.

**Comment by Munawwar** [comment]
I hit a problem with jsdom with the style syntax I proposed. The syntax isn't valid CSS values, so jsdom throws an error. The workaround is to use a sax-like html parser and remove invalid syntax during DOM construction. However this syntax can break assestgraph as well. So I am reconsidering the syntax...

**Comment by Munawwar** [comment]
Changed the syntax to do simpler li-style and li-class like for if and foreach (more like AnugularJS and React now).

**Comment by Munawwar** [comment]
Unwise to move away from KO syntax at this point. Closing issue.
