### ISSUE TITLE
provision of event-handles such as onclick etc in much simpler way

### ISSUE THREAD

**Issue by ashish-soni** [Munawwar/lithium-ui#3]
custom events exposed by components as different names (x-event)

**Comment by Munawwar** [comment]
This can be done when creating a new instance a component:
```html
<lui-button onclick="onClickHandler"></button>
```

However this cannot be done for one common use case: Most of the components in an app will inherit the wrapper div tag of Lui.Component. Hence they cannot add onclick etc to the wrapper div. So this feature wouldn't satisfy a common use case of a component trying to add event handlers to it's own root element (for components inheriting templates). So a JS solution is still required for this.

So I am thinking whether to have two ways to do similar things...hmmm.

**Comment by ashish-soni** [comment]
Within component template, Are events supported like with syntax like this ?

 <input type="button" value="Submit" on-click="handleClick()">

**Comment by ashish-soni** [comment]
Also for custom-events fired by component, you should have provisition to assign callback by container.
